[package]
name = "tracker-application"
description = "Application use cases for the Time Tracker"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
chrono = { workspace = true }
chrono-tz = { workspace = true }
thiserror = { workspace = true }
tracker-domain = { path = "../tracker-domain" }

[dev-dependencies]
uuid = { workspace = true }
